#include "slicer/Slicer.hpp"
#include <algorithm>
#include <cctype>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <limits>
#include <random>
#include <stdexcept>
#include <string>

namespace forgeslice::slicer {
namespace { constexpr double EPS=1e-7; constexpr double PI=3.14159265358979323846;
std::string lower(std::string s){for(char&c:s)c=static_cast<char>(std::tolower(static_cast<unsigned char>(c)));return s;}
std::vector<Segment2> intersect(const Triangle&t,double z){std::vector<Point2>p;auto edge=[&](const Vec3&a,const Vec3&b){bool c=(a.z<z&&b.z>z)||(a.z>z&&b.z<z);if(c){double q=(z-a.z)/(b.z-a.z);p.push_back({a.x+q*(b.x-a.x),a.y+q*(b.y-a.y)});}else if(std::abs(a.z-z)<EPS&&std::abs(b.z-z)>EPS)p.push_back({a.x,a.y});};edge(t.a,t.b);edge(t.b,t.c);edge(t.c,t.a);if(p.size()<2||std::hypot(p[0].x-p[1].x,p[0].y-p[1].y)<EPS)return{};return{{{p[0],p[1]}}};}
bool near(const Point2&a,const Point2&b){return std::hypot(a.x-b.x,a.y-b.y)<1e-4;}
double area(const std::vector<Point2>&p){double a=0;for(size_t i=0;i<p.size();++i){auto&q=p[i];auto&r=p[(i+1)%p.size()];a+=q.x*r.y-r.x*q.y;}return a*.5;}
std::vector<std::vector<Point2>> chain(std::vector<Segment2>s){std::vector<std::vector<Point2>>o;while(!s.empty()){auto x=s.back();s.pop_back();std::vector<Point2>l{x.a,x.b};while(!near(l.front(),l.back())){bool f=false;for(size_t i=0;i<s.size();++i){if(near(s[i].a,l.back())){l.push_back(s[i].b);s.erase(s.begin()+i);f=true;break;}if(near(s[i].b,l.back())){l.push_back(s[i].a);s.erase(s.begin()+i);f=true;break;}}if(!f)break;}if(l.size()>=3&&near(l.front(),l.back()))l.pop_back();if(l.size()>=3&&std::abs(area(l))>1e-8)o.push_back(std::move(l));}return o;}
bool inside(const Point2&p,const std::vector<Point2>&q){bool c=false;for(size_t i=0,j=q.size()-1;i<q.size();j=i){auto&a=q[i];auto&b=q[j];if(((a.y>p.y)!=(b.y>p.y))&&p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y+1e-30)+a.x)c=!c;}return c;}
bool insideAny(const Point2&p,const std::vector<std::vector<Point2>>&l){bool c=false;for(auto&q:l)if(inside(p,q))c=!c;return c;}
void bounds(const std::vector<std::vector<Point2>>&l,double&x0,double&x1,double&y0,double&y1){x0=std::numeric_limits<double>::infinity();x1=-x0;y0=std::numeric_limits<double>::infinity();y1=-y0;for(auto&q:l)for(auto&p:q){x0=std::min(x0,p.x);x1=std::max(x1,p.x);y0=std::min(y0,p.y);y1=std::max(y1,p.y);}}
template<class F>std::vector<Segment2>field(const std::vector<std::vector<Point2>>&l,double sp,F fn){std::vector<Segment2>o;if(sp<=0)return o;double x0,x1,y0,y1;bounds(l,x0,x1,y0,y1);double d=std::hypot(x1-x0,y1-y0),step=std::max(.16,sp*.45);for(double ph=-d;ph<=d;ph+=sp){std::vector<Point2>r;for(int n=0;n<=static_cast<int>(d/step)+4;++n){double u=n*step-d;Point2 p=fn(u,ph);if(p.x<x0-1||p.x>x1+1||p.y<y0-1||p.y>y1+1||!insideAny(p,l)){if(r.size()>=2)o.push_back({r.front(),r.back()});r.clear();continue;}if(!r.empty()&&!insideAny({(r.back().x+p.x)/2,(r.back().y+p.y)/2},l)){if(r.size()>=2)o.push_back({r.front(),r.back()});r.clear();}r.push_back(p);}if(r.size()>=2)o.push_back({r.front(),r.back()});}return o;}
std::vector<Segment2>lines(const std::vector<std::vector<Point2>>&l,double sp,double ang){double c=std::cos(ang),s=std::sin(ang);return field(l,sp,[=](double u,double ph){return Point2{c*u-s*ph,s*u+c*ph};});}
std::vector<Segment2>grid(const std::vector<std::vector<Point2>>&l,double sp,double a){auto o=lines(l,sp,a),q=lines(l,sp,a+PI/2);o.insert(o.end(),q.begin(),q.end());return o;}
std::vector<Segment2>tri(const std::vector<std::vector<Point2>>&l,double sp,double a){auto o=lines(l,sp,a),q=lines(l,sp,a+PI/3),r=lines(l,sp,a+2*PI/3);o.insert(o.end(),q.begin(),q.end());o.insert(o.end(),r.begin(),r.end());return o;}
std::vector<Segment2>hex(const std::vector<std::vector<Point2>>&l,double sp){std::vector<Segment2>o;double x0,x1,y0,y1;bounds(l,x0,x1,y0,y1);double r=sp*1.15,dx=1.5*r,dy=std::sqrt(3.)*r;int row=0;for(double cy=y0-dy;cy<=y1+dy;cy+=dy,++row)for(double cx=x0-dx;cx<=x1+dx;cx+=dx){double x=cx+(row%2)*.75*r;std::vector<Point2>h;for(int k=0;k<6;++k){double a=PI/6+k*PI/3;h.push_back({x+r*std::cos(a),cy+r*std::sin(a)});}for(int k=0;k<6;++k){auto a=h[k],b=h[(k+1)%6];if(insideAny({(a.x+b.x)/2,(a.y+b.y)/2},l))o.push_back({a,b});}}return o;}
std::vector<Segment2>concentric(const std::vector<std::vector<Point2>>&l,double sp){std::vector<Segment2>o;for(auto&q:l){double cx=0,cy=0;for(auto&p:q){cx+=p.x;cy+=p.y;}cx/=q.size();cy/=q.size();double rad=std::sqrt(std::abs(area(q))/PI);for(int k=0;k<static_cast<int>(rad/std::max(sp,.05));++k){double f=1.-(k+1)*sp/(rad+sp);if(f<=.05)break;std::vector<Point2>w;for(auto&p:q)w.push_back({cx+(p.x-cx)*f,cy+(p.y-cy)*f});for(size_t i=0;i<w.size();++i)if(insideAny({(w[i].x+w[(i+1)%w.size()].x)/2,(w[i].y+w[(i+1)%w.size()].y)/2},l))o.push_back({w[i],w[(i+1)%w.size()]});}}return o;}
std::vector<Segment2>pattern(const std::vector<std::vector<Point2>>&l,double sp,InfillPattern p,int layer){double a=(layer%2)?PI/2:0;switch(p){case InfillPattern::Rectilinear:case InfillPattern::Lines:case InfillPattern::ZigZag:return lines(l,sp,a);case InfillPattern::Grid:return grid(l,sp,a);case InfillPattern::Cross:return grid(l,sp*1.35,a);case InfillPattern::Cross3D:return grid(l,sp*1.5,(layer%4)*PI/4);case InfillPattern::Triangles:case InfillPattern::Octet:return tri(l,sp*1.35,a);case InfillPattern::TriHexagon:return tri(l,sp*1.25,a);case InfillPattern::Honeycomb:case InfillPattern::Hexagon:return hex(l,sp);case InfillPattern::Cubic:case InfillPattern::AdaptiveCubic:return grid(l,sp*1.45,a+(layer%3)*PI/6);case InfillPattern::CubicSubdivision:return grid(l,sp*1.7,a+(layer%3)*PI/6);case InfillPattern::Gyroid:{double k=2*PI/std::max(sp*4.,.5);return field(l,sp*.65,[=](double u,double ph){return Point2{u,ph+u*.22*std::sin(k*u+ph*k)};});}case InfillPattern::Concentric:return concentric(l,sp);case InfillPattern::Hilbert:case InfillPattern::Scaffolding:return grid(l,sp*1.8,a);case InfillPattern::ArchimedeanChords:case InfillPattern::Stars:return tri(l,sp*1.6,a);case InfillPattern::Lightning:return lines(l,sp*2.,a);case InfillPattern::AdaptiveLines:return lines(l,sp,a);case InfillPattern::Voronoi:return hex(l,sp*1.35);case InfillPattern::Random:{auto o=lines(l,sp*1.25,a);std::mt19937 g(0xF05E + layer);std::shuffle(o.begin(),o.end(),g);return o;}case InfillPattern::Hilbert3D:return grid(l,sp*1.8,(layer%4)*PI/4);case InfillPattern::Sierpinski:return tri(l,sp*1.8,a);}return lines(l,sp,a);}
void move(std::ofstream&o,const Point2&p,double z,double speed,double&e,const Point2*from,bool ex,double width,double h,double filament){o<<"G1 X"<<std::fixed<<std::setprecision(3)<<p.x<<" Y"<<p.y<<" Z"<<z;if(ex&&from){double len=std::hypot(p.x-from->x,p.y-from->y),fa=PI*std::pow(filament/2.,2);e+=len*width*h/fa;o<<" E"<<std::setprecision(5)<<e;}o<<" F"<<std::setprecision(0)<<speed*60<<"\n";}
}
const char*infillPatternName(InfillPattern p){static const char*n[]={"rectilinear","grid","lines","zigzag","cross","cross3d","triangles","trihexagon","honeycomb","hexagon","cubic","cubic-subdivision","octet","gyroid","concentric","hilbert","archimedean-chords","stars","scaffolding","lightning","adaptive-lines","adaptive-cubic","voronoi","random","hilbert3d","sierpinski"};return n[static_cast<int>(p)];}
InfillPattern infillPatternFromString(const std::string&v){std::string s=lower(v);for(int i=0;i<26;++i)if(s==infillPatternName(static_cast<InfillPattern>(i)))return static_cast<InfillPattern>(i);if(s=="cubic subdivision")return InfillPattern::CubicSubdivision;if(s=="tri-hexagon")return InfillPattern::TriHexagon;throw std::invalid_argument("Unknown infill pattern: "+v);}
std::vector<std::string>availableInfillPatterns(){std::vector<std::string>v;for(int i=0;i<26;++i)v.emplace_back(infillPatternName(static_cast<InfillPattern>(i)));return v;}
std::vector<SliceLayer>Slicer::slice(const Mesh&m)const{if(m.empty())throw std::runtime_error("Cannot slice an empty mesh");if(settings_.layer_height_mm<=0||settings_.first_layer_height_mm<=0)throw std::runtime_error("Layer height must be positive");std::vector<SliceLayer>r;double start=m.min.z+settings_.first_layer_height_mm*.5;for(double z=start;z<=m.max.z+EPS;z+=settings_.layer_height_mm){std::vector<Segment2>s;for(auto&t:m.triangles){auto x=intersect(t,z);s.insert(s.end(),x.begin(),x.end());}auto l=chain(std::move(s));if(!l.empty())r.push_back({z,std::move(l)});}return r;}
void Slicer::writeGcode(const Mesh&m,const std::string&file)const{auto layers=slice(m);std::ofstream o(file);if(!o)throw std::runtime_error("Could not create G-code: "+file);o<<"; ForgeSlice 0.3\n; Printer: FlashForge Adventurer 5M Pro\n; Pattern: "<<infillPatternName(settings_.infill_pattern)<<"\n; Layers: "<<layers.size()<<"\nG90\nM82\nG28\nM104 S200\nM140 S60\nM109 S200\nM190 S60\n";double e=0;double density=std::clamp(settings_.infill_percent,0.,100.);for(size_t li=0;li<layers.size();++li){auto&layer=layers[li];o<<";LAYER:"<<li<<"\n";for(auto&loop:layer.loops){if(loop.size()<3)continue;double cx=0,cy=0;for(auto&p:loop){cx+=p.x;cy+=p.y;}cx/=loop.size();cy/=loop.size();for(int w=0;w<std::max(1,settings_.walls);++w){double f=1.-(w*settings_.line_width_mm)/std::max(settings_.line_width_mm*2.,25.);std::vector<Point2>wall;for(auto&p:loop)wall.push_back({cx+(p.x-cx)*f,cy+(p.y-cy)*f});move(o,wall.front(),layer.z,settings_.travel_speed_mm_s,e,nullptr,false,settings_.line_width_mm,settings_.layer_height_mm,settings_.filament_diameter_mm);Point2 prev=wall.front();for(size_t j=1;j<=wall.size();++j){auto p=wall[j%wall.size()];move(o,p,layer.z,settings_.print_speed_mm_s,e,&prev,true,settings_.line_width_mm,settings_.layer_height_mm,settings_.filament_diameter_mm);prev=p;}}}bool solid=static_cast<int>(li)<settings_.bottom_layers||(static_cast<int>(layers.size())-static_cast<int>(li))<=settings_.top_layers;double d=solid?100.:density;double sp=d>0?settings_.line_width_mm*100./d:0;if(d>0){auto seg=pattern(layer.loops,sp,settings_.infill_pattern,static_cast<int>(li));bool rev=false;for(auto&s:seg){Point2 a=rev?s.b:s.a,b=rev?s.a:s.b;move(o,a,layer.z,settings_.travel_speed_mm_s,e,nullptr,false,settings_.line_width_mm,settings_.layer_height_mm,settings_.filament_diameter_mm);move(o,b,layer.z,settings_.print_speed_mm_s,e,&a,true,settings_.line_width_mm,settings_.layer_height_mm,settings_.filament_diameter_mm);rev=!rev;}}}o<<"M104 S0\nM140 S0\nG28 X0\nM84\n";}
} // namespace forgeslice::slicer
